import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import fs from 'fs'
import path from 'path'

// Read version from public/version.json (generated by generate-version.js)
let appVersion = ''
try {
    const versionFile = path.resolve(__dirname, 'public/version.json')
    if (fs.existsSync(versionFile)) {
        const data = JSON.parse(fs.readFileSync(versionFile, 'utf-8'))
        appVersion = data.version
    }
} catch (e) {
    console.warn('Failed to read version.json')
}

// Fallback to direct git hash if version is still empty
if (!appVersion) {
    try {
        const { execSync } = await import('child_process')
        appVersion = execSync('git rev-parse --short HEAD').toString().trim()
        console.log(`[ViteConfig] Version fallback to git: ${appVersion}`)
    } catch (e) {
        appVersion = Date.now().toString()
        console.warn(`[ViteConfig] Version fallback to timestamp: ${appVersion}`)
    }
}

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        VitePWA({
            registerType: 'autoUpdate',
            injectRegister: 'auto',
            workbox: {
                skipWaiting: true,
                clientsClaim: true,
                cleanupOutdatedCaches: true, // 로컬 캐시와 서버 버전 충돌 방지
                maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
                navigateFallbackDenylist: [/^\/api/], // API 요청은 Service Worker가 가로채지 않음
            },
            includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.svg'],
            manifest: {
                name: 'Grapplay',
                short_name: 'Grapplay',
                description: '프리미엄 주짓수 기술 영상 플랫폼',
                theme_color: '#09090b',
                background_color: '#09090b',
                display: 'standalone',
                start_url: '/',
                icons: [
                    {
                        src: 'pwa-192x192.png',
                        sizes: '192x192',
                        type: 'image/png',
                        purpose: 'any maskable'
                    },
                    {
                        src: 'pwa-512x512.png',
                        sizes: '512x512',
                        type: 'image/png',
                        purpose: 'any maskable'
                    }
                ]
            }
        }),
    ],
    define: {
        'import.meta.env.VITE_APP_VERSION': JSON.stringify(appVersion),
    },
    build: {
        rollupOptions: {
            output: {
                manualChunks: (id) => {
                    // React 관련 라이브러리
                    if (id.includes('node_modules/react') ||
                        id.includes('node_modules/react-dom') ||
                        id.includes('node_modules/react-router')) {
                        return 'react-vendor';
                    }

                    // Supabase 클라이언트
                    if (id.includes('@supabase/supabase-js')) {
                        return 'supabase';
                    }

                    // React Query
                    if (id.includes('@tanstack/react-query')) {
                        return 'react-query';
                    }

                    // 비디오 관련
                    if (id.includes('@vimeo/player') || id.includes('tus-js-client')) {
                        return 'video';
                    }

                    // 무거운 라이브러리들 - 별도 청크로 분리
                    if (id.includes('framer-motion')) {
                        return 'framer-motion';
                    }

                    if (id.includes('reactflow')) {
                        return 'reactflow';
                    }

                    if (id.includes('recharts')) {
                        return 'recharts';
                    }

                    // DnD Kit
                    if (id.includes('@dnd-kit')) {
                        return 'dnd-kit';
                    }

                    // UI 라이브러리
                    if (id.includes('lucide-react') || id.includes('date-fns')) {
                        return 'ui';
                    }

                    // Admin 페이지들 - 별도 청크
                    if (id.includes('/pages/admin/')) {
                        return 'admin-pages';
                    }

                    // Creator 페이지들 - 별도 청크
                    if (id.includes('/pages/creator/')) {
                        return 'creator-pages';
                    }
                }
            }
        },
        chunkSizeWarningLimit: 1000, // 경고 임계값 상향 (1MB)
        minify: 'terser', // 더 강력한 압축
        terserOptions: {
            compress: {
                drop_console: true, // 프로덕션에서 console.log 제거
                drop_debugger: true,
                pure_funcs: ['console.log', 'console.info', 'console.debug']
            }
        },
        sourcemap: false, // 프로덕션 빌드에서 소스맵 제거 (크기 절약)
    },
    esbuild: {
        drop: process.env.NODE_ENV === 'production' ? ['console', 'debugger'] : [],
    },
    server: {
        // port: 8080, // Removed to allow default (5173) or flexible port
        open: true,
        proxy: {
            '/process': {
                target: 'http://localhost:8081',
                changeOrigin: true,
            },
            '/api': {
                target: 'http://localhost:8081',
                changeOrigin: true,
            },
            '/temp': {
                target: 'http://localhost:8081',
                changeOrigin: true,
            }
        }
    }
})

// Touch to force reload

// Touch to force reload
