import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'
import fs from 'fs'
import path from 'path'

// Read version from public/version.json (generated by generate-version.js)
let appVersion = ''
try {
    const versionFile = path.resolve(__dirname, 'public/version.json')
    if (fs.existsSync(versionFile)) {
        const data = JSON.parse(fs.readFileSync(versionFile, 'utf-8'))
        appVersion = data.version
    }
} catch (e) {
    console.warn('Failed to read version.json')
}

// Fallback to direct git hash if version is still empty
if (!appVersion) {
    try {
        const { execSync } = await import('child_process')
        appVersion = execSync('git rev-parse --short HEAD').toString().trim()
        console.log(`[ViteConfig] Version fallback to git: ${appVersion}`)
    } catch (e) {
        appVersion = Date.now().toString()
        console.warn(`[ViteConfig] Version fallback to timestamp: ${appVersion}`)
    }
}

// https://vitejs.dev/config/
export default defineConfig({
    plugins: [
        react(),
        VitePWA({
            // ✅ PWA 설치 기능만 유지, 자동 업데이트 비활성화 (무한 새로고침 방지)
            registerType: 'prompt', // 'autoUpdate' → 'prompt': 사용자가 직접 업데이트 결정
            injectRegister: 'auto',
            workbox: {
                // ❌ skipWaiting/clientsClaim 비활성화 - 즉시 takeover 방지
                skipWaiting: false,
                clientsClaim: false,
                cleanupOutdatedCaches: true,
                // ❌ JS/CSS/HTML 캐싱 완전 비활성화 - 브라우저 기본 캐싱만 사용
                globPatterns: [], // 아무것도 precache 안 함
                navigateFallback: null,
                // ✅ 런타임 캐싱도 최소화: 폰트만 캐시
                runtimeCaching: [
                    // Fonts만 캐시 (거의 안 바뀜)
                    {
                        urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
                        handler: 'CacheFirst',
                        options: {
                            cacheName: 'google-fonts-cache',
                            expiration: { maxEntries: 10, maxAgeSeconds: 60 * 60 * 24 * 365 }
                        }
                    },
                    {
                        urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
                        handler: 'CacheFirst',
                        options: {
                            cacheName: 'gstatic-fonts-cache',
                            expiration: { maxEntries: 20, maxAgeSeconds: 60 * 60 * 24 * 365 }
                        }
                    }
                    // 나머지는 모두 브라우저 기본 동작 (네트워크 요청)
                ]
            },
            includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.svg'],
            manifest: {
                name: 'Grapplay',
                short_name: 'Grapplay',
                description: '프리미엄 주짓수 기술 영상 플랫폼',
                theme_color: '#09090b',
                background_color: '#09090b',
                display: 'standalone',
                start_url: '/',
                icons: [
                    {
                        src: 'pwa-192x192.png',
                        sizes: '192x192',
                        type: 'image/png',
                        purpose: 'any maskable'
                    },
                    {
                        src: 'pwa-512x512.png',
                        sizes: '512x512',
                        type: 'image/png',
                        purpose: 'any maskable'
                    }
                ]
            }
        }),
    ],
    define: {
        'import.meta.env.VITE_APP_VERSION': JSON.stringify(appVersion),
    },
    build: {
        // 무거운 차트 라이브러리를 초기 로딩에서 제외 (Safari 성능 개선)
        modulePreload: {
            resolveDependencies: (filename, deps) => {
                // recharts/d3는 차트 페이지에서만 필요하므로 초기 preload에서 제외
                return deps.filter(dep =>
                    !dep.includes('recharts') &&
                    !dep.includes('vendor-d3') &&
                    !dep.includes('framer') // 애니메이션도 제외
                );
            }
        },
        rollupOptions: {
            output: {
                manualChunks: (id) => {
                    // 핵심 React 라이브러리 (항상 필요)
                    if (id.includes('node_modules/react/') ||
                        id.includes('node_modules/react-dom/') ||
                        id.includes('node_modules/scheduler/')) {
                        return 'react-core';
                    }

                    // React Router (라우팅)
                    if (id.includes('react-router') || id.includes('@remix-run')) {
                        return 'react-router';
                    }

                    // 무거운 라이브러리 분리
                    if (id.includes('@supabase')) return 'supabase';
                    if (id.includes('@sentry')) return 'sentry';
                    // recharts와 d3는 서로 의존성이 있어 초기화 순서 문제 발생 가능
                    // 각각 별도 청크로 분리하고 d3를 먼저 로드되도록 함
                    if (id.includes('d3-')) return 'vendor-d3';
                    if (id.includes('recharts')) return 'vendor-recharts';
                    if (id.includes('reactflow') || id.includes('@reactflow')) return 'reactflow';
                    if (id.includes('framer-motion')) return 'framer';
                    if (id.includes('@tanstack/react-query')) return 'react-query';
                    if (id.includes('date-fns')) return 'date-fns';
                    if (id.includes('@vimeo/player')) return 'vimeo';
                    if (id.includes('tus-js-client')) return 'tus';
                    if (id.includes('lucide-react')) return 'icons';
                    if (id.includes('@radix-ui')) return 'radix';
                    if (id.includes('zod')) return 'zod';
                    if (id.includes('embla-carousel')) return 'embla';
                    if (id.includes('@mux')) return 'mux';
                    if (id.includes('@upchunk') || id.includes('upchunk')) return 'upchunk';
                    if (id.includes('@dnd-kit')) return 'dnd-kit';
                    if (id.includes('@paypal')) return 'paypal';
                    if (id.includes('@stripe')) return 'stripe';
                }
            }
        },
        chunkSizeWarningLimit: 1000, // 경고 임계값 상향 (1MB)
        sourcemap: false, // 프로덕션 빌드에서 소스맵 제거 (크기 절약)
        // esbuild 설정 - d3/recharts 호환성을 위해 보수적 최적화
        target: 'es2020',
        minify: true,
    },
    server: {
        // port: 8080, // Removed to allow default (5173) or flexible port
        open: true,
        proxy: {
            '/process': {
                target: 'http://localhost:8081',
                changeOrigin: true,
            },
            '/api': {
                target: 'http://localhost:8081',
                changeOrigin: true,
            },
            '/temp': {
                target: 'http://localhost:8081',
                changeOrigin: true,
            }
        }
    }
})

// Touch to force Vercel rebuild
